[phases.setup]
nixPkgs = ["php81", "php81Extensions.pdo", "php81Extensions.pdo_pgsql"]

[phases.build]
cmds = ["composer install --ignore-platform-reqs"]

[deploy]
startCommand = "php -S 0.0.0.0:${PORT} -t ."
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10