[phases.setup]
nixPkgs = ["php81", "php81Packages.composer", "php81Extensions.pdo", "php81Extensions.pdo_pgsql"]

[phases.build]
cmds = ["composer install --ignore-platform-reqs"]

[deploy]
startCommand = "php -S 0.0.0.0:8080 -t ."
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[build]
builder = "dockerfile"